
Oct 22 16:45:56 controller systemd[1]: Started kubelet.service - kubelet: The Kubernetes Node Agent.
░░ Subject: A start job for unit kubelet.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit kubelet.service has finished successfully.
░░ 
░░ The job identifier is 152.
Oct 22 16:45:57 controller kubelet[854]: Flag --container-runtime-endpoint has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Oct 22 16:45:57 controller kubelet[854]: Flag --pod-infra-container-image has been deprecated, will be removed in a future release. Image garbage collector will get sandbox image information from CRI.
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.501418     854 server.go:203] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.520699     854 server.go:467] "Kubelet version" kubeletVersion="v1.28.14"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.520748     854 server.go:469] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.521238     854 server.go:895] "Client rotation is on, will bootstrap in background"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.534666     854 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.574375     854 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.636959     854 server.go:725] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.641732     854 container_manager_linux.go:265] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.642051     854 container_manager_linux.go:270] "Creating Container Manager object based on Node Config" nodeConfig={"RuntimeCgroupsName":"","SystemCgroupsName":"","KubeletCgroupsName":"","KubeletOOMScoreAdj":-999,"ContainerRuntime":"","CgroupsPerQOS":true,"CgroupRoot":"/","CgroupDriver":"systemd","KubeletRootDir":"/var/lib/kubelet","ProtectKernelDefaults":false,"KubeReservedCgroupName":"","SystemReservedCgroupName":"","ReservedSystemCPUs":{},"EnforceNodeAllocatable":{"pods":{}},"KubeReserved":null,"SystemReserved":null,"HardEvictionThresholds":[{"Signal":"memory.available","Operator":"LessThan","Value":{"Quantity":"100Mi","Percentage":0},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.1},"GracePeriod":0,"MinReclaim":null},{"Signal":"nodefs.inodesFree","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.05},"GracePeriod":0,"MinReclaim":null},{"Signal":"imagefs.available","Operator":"LessThan","Value":{"Quantity":null,"Percentage":0.15},"GracePeriod":0,"MinReclaim":null}],"QOSReserved":{},"CPUManagerPolicy":"none","CPUManagerPolicyOptions":null,"TopologyManagerScope":"container","CPUManagerReconcilePeriod":10000000000,"ExperimentalMemoryManagerPolicy":"None","ExperimentalMemoryManagerReservedMemory":null,"PodPidsLimit":-1,"EnforceCPULimits":true,"CPUCFSQuotaPeriod":100000000,"TopologyManagerPolicy":"none","TopologyManagerPolicyOptions":null}
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.643029     854 topology_manager.go:138] "Creating topology manager with none policy"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.643088     854 container_manager_linux.go:301] "Creating device plugin manager"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.645295     854 state_mem.go:36] "Initialized new in-memory state store"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.651173     854 kubelet.go:393] "Attempting to sync node with API server"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.651230     854 kubelet.go:298] "Adding static pod path" path="/etc/kubernetes/manifests"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.656285     854 kubelet.go:309] "Adding apiserver pod source"
Oct 22 16:45:57 controller kubelet[854]: W1022 16:45:57.657939     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.658180     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.659652     854 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.665024     854 kuberuntime_manager.go:259] "Container runtime initialized" containerRuntime="containerd" version="1.7.12" apiVersion="v1"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.677810     854 server.go:1232] "Started kubelet"
Oct 22 16:45:57 controller kubelet[854]: W1022 16:45:57.678046     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.678188     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.686488     854 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.692288     854 server.go:162] "Starting to listen" address="0.0.0.0" port=10250
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.694348     854 server.go:462] "Adding debug handlers to kubelet server"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.698759     854 ratelimit.go:65] "Setting rate limiting for podresources endpoint" qps=100 burstTokens=10
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.699632     854 server.go:233] "Starting to serve the podresources API" endpoint="unix:/var/lib/kubelet/pod-resources/kubelet.sock"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.707627     854 scope.go:117] "RemoveContainer" containerID="ee1ecc890bb5b44f7a07c6b6e1d143aaea119499fcd19febc4ec69a91d34df79"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.709278     854 volume_manager.go:291] "Starting Kubelet Volume Manager"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.709478     854 cri_stats_provider.go:448] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.709500     854 kubelet.go:1431] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.709609     854 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"controller.1800d42f915e6919", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"controller", UID:"controller", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"controller"}, FirstTimestamp:time.Date(2024, time.October, 22, 16, 45, 57, 677705497, time.Local), LastTimestamp:time.Date(2024, time.October, 22, 16, 45, 57, 677705497, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"kubelet", ReportingInstance:"controller"}': 'Post "https://192.168.1.120:6443/api/v1/namespaces/default/events": dial tcp 192.168.1.120:6443: connect: connection refused'(may retry after sleeping)
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.711011     854 desired_state_of_world_populator.go:151] "Desired state populator starts to run"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.722243     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused" interval="200ms"
Oct 22 16:45:57 controller kubelet[854]: W1022 16:45:57.726454     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.726495     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.766028     854 scope.go:117] "RemoveContainer" containerID="b0c2d7e70a5c1c4b2c4223abd2e53a8f1f745c62100b624a29e92fba97425a53"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.777613     854 reconciler_new.go:29] "Reconciler: start to sync state"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.807875     854 scope.go:117] "RemoveContainer" containerID="7018a099198b1243543b28e7d1d01521319d84d42d3e92688a016b7ed865a43b"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.823612     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.829801     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": dial tcp 192.168.1.120:6443: connect: connection refused" node="controller"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.840442     854 cpu_manager.go:214] "Starting CPU manager" policy="none"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.840483     854 cpu_manager.go:215] "Reconciling" reconcilePeriod="10s"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.840517     854 state_mem.go:36] "Initialized new in-memory state store"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.843538     854 scope.go:117] "RemoveContainer" containerID="2344120d74564612936407e10010f1b8ffd568716d1a7f3519bdc7d75448ca89"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.846675     854 state_mem.go:88] "Updated default CPUSet" cpuSet=""
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.846820     854 state_mem.go:96] "Updated CPUSet assignments" assignments={}
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.847446     854 policy_none.go:49] "None policy: Start"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.853792     854 memory_manager.go:169] "Starting memorymanager" policy="None"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.853849     854 state_mem.go:35] "Initializing new in-memory state store"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.858590     854 state_mem.go:75] "Updated machine memory state"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.874114     854 scope.go:117] "RemoveContainer" containerID="6d5756e7641cc67e1d878011c9269c497cd25ac28b3919110e493b30cf4f3b6b"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.897620     854 scope.go:117] "RemoveContainer" containerID="30ee8f645365d1241e3d3b01aba83fe0328c5fdabd7de578837053f116899ad9"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.902532     854 kubelet_network_linux.go:50] "Initialized iptables rules." protocol="IPv4"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.906774     854 kubelet_network_linux.go:50] "Initialized iptables rules." protocol="IPv6"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.907454     854 status_manager.go:217] "Starting to sync pod status with apiserver"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.907689     854 kubelet.go:2321] "Starting kubelet main sync loop"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.908311     854 kubelet.go:2345] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.929358     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused" interval="400ms"
Oct 22 16:45:57 controller kubelet[854]: W1022 16:45:57.929757     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.929909     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.930037     854 scope.go:117] "RemoveContainer" containerID="c59d48412a48d460d321e94bcc272de722a5781724669dd26b970bc556037fe2"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.964738     854 scope.go:117] "RemoveContainer" containerID="ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.974140     854 manager.go:471] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Oct 22 16:45:57 controller kubelet[854]: I1022 16:45:57.980788     854 plugin_manager.go:118] "Starting Kubelet Plugin Manager"
Oct 22 16:45:57 controller kubelet[854]: E1022 16:45:57.981520     854 eviction_manager.go:258] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"controller\" not found"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.011724     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="30ee8f645365d1241e3d3b01aba83fe0328c5fdabd7de578837053f116899ad9"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.012845     854 topology_manager.go:215] "Topology Admit Handler" podUID="445865841952f2600d032506c2391582" podNamespace="kube-system" podName="etcd-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.018562     854 topology_manager.go:215] "Topology Admit Handler" podUID="0e229e334952ac434602f5f643efb497" podNamespace="kube-system" podName="kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.025544     854 topology_manager.go:215] "Topology Admit Handler" podUID="1be0ed11a85b027244bfec235c57c498" podNamespace="kube-system" podName="kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.027558     854 topology_manager.go:215] "Topology Admit Handler" podUID="7367777219db54a576f0f8b0365a6c1f" podNamespace="kube-system" podName="kube-scheduler-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.038007     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039033     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="3cd4bc95d13899bc0eb09bcd52682c2eac4cd63716712022e810e577de6d5cdf"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039051     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="752b6be7fd71c68c0ffc1afbf86a4e7591c3f4e117f57821f5e05ce8f3a887b1"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039062     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="bafd68c98f2d3cb34c37eb72b9993aa222b2c14075641cfca9fe8df24ffa11fb"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039068     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="ed91beca19a37af2236fa3c6db2e97b0afa60ee77d692b6ae6244684f9382e26"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039082     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="764072e0defc57d2d7892c30eea13bf125f1aa74be565d38e4f39613a58fca81"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039092     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="ea9a1ee9ad62b25dbf7716a9c9b7f492008ad9eb1d844dec94fe513866e59cb0"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039102     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="59ee10b522f291235b3fdce957fac09f04da653e9a2f834deac48e8c723ebb94"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039108     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="a8f7792225a35f7a5370aa6538477bdc378c9497dc62fec68ed740003c52929b"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.039132     854 scope.go:117] "RemoveContainer" containerID="ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9"
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.039598     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": dial tcp 192.168.1.120:6443: connect: connection refused" node="controller"
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.053424     854 remote_runtime.go:432] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find container \"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9\": not found" containerID="ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.053576     854 pod_container_deletor.go:53] "DeleteContainer returned error" containerID={"Type":"containerd","ID":"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9"} err="failed to get container status \"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9\": rpc error: code = NotFound desc = an error occurred when try to find container \"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9\": not found"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.053617     854 scope.go:117] "RemoveContainer" containerID="ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.064771     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="28bbb633fcd3e8b6b219e5196fc946ee3c31b267cec8c1ca5cc78a8b1190ed4b"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.067726     854 pod_container_deletor.go:53] "DeleteContainer returned error" containerID={"Type":"containerd","ID":"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9"} err="failed to get container status \"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9\": rpc error: code = NotFound desc = an error occurred when try to find container \"ecb565ae2f47f4c03ea3eb3217ce4969d1c661e7eb50801271520f8aec449cc9\": not found"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.087059     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="c59d48412a48d460d321e94bcc272de722a5781724669dd26b970bc556037fe2"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.087090     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="cc8df02096123630711ef1610249b001b3439103ec868268e5e6d2896a15f6f0"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.087098     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="a6310e92d60a7e7e2989227a7ab907e316118677c3cbbf7d6c48d0a746b9275f"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.120340     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="929565f37b34f1a61cfc1804525a3f227b35217260dcba79250fcff1c7b8e178"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.120361     854 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="4c1db3ffbd35374c10681ca7473dd2de89470885c730a05e20661c56fe648f3f"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.193632     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-etc-ca-certificates\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.193894     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-k8s-certs\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194018     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-kubeconfig\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194048     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/0e229e334952ac434602f5f643efb497-k8s-certs\") pod \"kube-apiserver-controller\" (UID: \"0e229e334952ac434602f5f643efb497\") " pod="kube-system/kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194064     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/0e229e334952ac434602f5f643efb497-usr-share-ca-certificates\") pod \"kube-apiserver-controller\" (UID: \"0e229e334952ac434602f5f643efb497\") " pod="kube-system/kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194078     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/0e229e334952ac434602f5f643efb497-ca-certs\") pod \"kube-apiserver-controller\" (UID: \"0e229e334952ac434602f5f643efb497\") " pod="kube-system/kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194097     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/0e229e334952ac434602f5f643efb497-etc-ca-certificates\") pod \"kube-apiserver-controller\" (UID: \"0e229e334952ac434602f5f643efb497\") " pod="kube-system/kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194127     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-pki\" (UniqueName: \"kubernetes.io/host-path/0e229e334952ac434602f5f643efb497-etc-pki\") pod \"kube-apiserver-controller\" (UID: \"0e229e334952ac434602f5f643efb497\") " pod="kube-system/kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194140     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"ca-certs\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-ca-certs\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194154     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-certs\" (UniqueName: \"kubernetes.io/host-path/445865841952f2600d032506c2391582-etcd-certs\") pod \"etcd-controller\" (UID: \"445865841952f2600d032506c2391582\") " pod="kube-system/etcd-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194168     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etcd-data\" (UniqueName: \"kubernetes.io/host-path/445865841952f2600d032506c2391582-etcd-data\") pod \"etcd-controller\" (UID: \"445865841952f2600d032506c2391582\") " pod="kube-system/etcd-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194183     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-flexvolume-dir\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194199     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-usr-share-ca-certificates\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194216     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-usr-local-share-ca-certificates\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194230     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/7367777219db54a576f0f8b0365a6c1f-kubeconfig\") pod \"kube-scheduler-controller\" (UID: \"7367777219db54a576f0f8b0365a6c1f\") " pod="kube-system/kube-scheduler-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194291     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/0e229e334952ac434602f5f643efb497-usr-local-share-ca-certificates\") pod \"kube-apiserver-controller\" (UID: \"0e229e334952ac434602f5f643efb497\") " pod="kube-system/kube-apiserver-controller"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.194371     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"etc-pki\" (UniqueName: \"kubernetes.io/host-path/1be0ed11a85b027244bfec235c57c498-etc-pki\") pod \"kube-controller-manager-controller\" (UID: \"1be0ed11a85b027244bfec235c57c498\") " pod="kube-system/kube-controller-manager-controller"
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.332315     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused" interval="800ms"
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.371324     854 remote_runtime.go:222] "StopPodSandbox from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find sandbox \"59ee10b522f291235b3fdce957fac09f04da653e9a2f834deac48e8c723ebb94\": not found" podSandboxID="59ee10b522f291235b3fdce957fac09f04da653e9a2f834deac48e8c723ebb94"
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.442013     854 remote_runtime.go:222] "StopPodSandbox from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find sandbox \"752b6be7fd71c68c0ffc1afbf86a4e7591c3f4e117f57821f5e05ce8f3a887b1\": not found" podSandboxID="752b6be7fd71c68c0ffc1afbf86a4e7591c3f4e117f57821f5e05ce8f3a887b1"
Oct 22 16:45:58 controller kubelet[854]: I1022 16:45:58.450281     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.450999     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": dial tcp 192.168.1.120:6443: connect: connection refused" node="controller"
Oct 22 16:45:58 controller kubelet[854]: W1022 16:45:58.524766     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.526028     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: W1022 16:45:58.781910     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.782086     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: W1022 16:45:58.784302     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.784340     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: W1022 16:45:58.914462     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:58 controller kubelet[854]: E1022 16:45:58.914592     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:45:59 controller kubelet[854]: E1022 16:45:59.137035     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused" interval="1.6s"
Oct 22 16:45:59 controller kubelet[854]: I1022 16:45:59.259903     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:45:59 controller kubelet[854]: E1022 16:45:59.267559     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": dial tcp 192.168.1.120:6443: connect: connection refused" node="controller"
Oct 22 16:46:00 controller kubelet[854]: W1022 16:46:00.608755     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:00 controller kubelet[854]: E1022 16:46:00.608961     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:00 controller kubelet[854]: W1022 16:46:00.733185     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:00 controller kubelet[854]: E1022 16:46:00.733288     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:00 controller kubelet[854]: E1022 16:46:00.740672     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused" interval="3.2s"
Oct 22 16:46:00 controller kubelet[854]: I1022 16:46:00.879812     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:46:00 controller kubelet[854]: E1022 16:46:00.880671     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": dial tcp 192.168.1.120:6443: connect: connection refused" node="controller"
Oct 22 16:46:04 controller kubelet[854]: I1022 16:46:04.084444     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:46:07 controller kubelet[854]: E1022 16:46:07.982661     854 eviction_manager.go:258] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"controller\" not found"
Oct 22 16:46:11 controller kubelet[854]: W1022 16:46:11.365516     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:11 controller kubelet[854]: I1022 16:46:11.365615     854 trace.go:236] Trace[1508982637]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229 (22-Oct-2024 16:46:01.364) (total time: 10001ms):
Oct 22 16:46:11 controller kubelet[854]: Trace[1508982637]: ---"Objects listed" error:Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": net/http: TLS handshake timeout 10001ms (16:46:11.365)
Oct 22 16:46:11 controller kubelet[854]: Trace[1508982637]: [10.001513641s] [10.001513641s] END
Oct 22 16:46:11 controller kubelet[854]: E1022 16:46:11.365633     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:11 controller kubelet[854]: W1022 16:46:11.375229     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:11 controller kubelet[854]: I1022 16:46:11.375425     854 trace.go:236] Trace[1461206523]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229 (22-Oct-2024 16:46:01.374) (total time: 10001ms):
Oct 22 16:46:11 controller kubelet[854]: Trace[1461206523]: ---"Objects listed" error:Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": net/http: TLS handshake timeout 10000ms (16:46:11.375)
Oct 22 16:46:11 controller kubelet[854]: Trace[1461206523]: [10.0010296s] [10.0010296s] END
Oct 22 16:46:11 controller kubelet[854]: E1022 16:46:11.375442     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:13 controller kubelet[854]: E1022 16:46:13.943881     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": context deadline exceeded" interval="6.4s"
Oct 22 16:46:14 controller kubelet[854]: E1022 16:46:14.086523     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": net/http: TLS handshake timeout" node="controller"
Oct 22 16:46:14 controller kubelet[854]: W1022 16:46:14.721408     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:14 controller kubelet[854]: I1022 16:46:14.721500     854 trace.go:236] Trace[421980424]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229 (22-Oct-2024 16:46:04.719) (total time: 10002ms):
Oct 22 16:46:14 controller kubelet[854]: Trace[421980424]: ---"Objects listed" error:Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": net/http: TLS handshake timeout 10002ms (16:46:14.721)
Oct 22 16:46:14 controller kubelet[854]: Trace[421980424]: [10.002175476s] [10.002175476s] END
Oct 22 16:46:14 controller kubelet[854]: E1022 16:46:14.721524     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:16 controller kubelet[854]: W1022 16:46:16.891927     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:16 controller kubelet[854]: I1022 16:46:16.892077     854 trace.go:236] Trace[965116472]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229 (22-Oct-2024 16:46:06.889) (total time: 10001ms):
Oct 22 16:46:16 controller kubelet[854]: Trace[965116472]: ---"Objects listed" error:Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": net/http: TLS handshake timeout 10001ms (16:46:16.891)
Oct 22 16:46:16 controller kubelet[854]: Trace[965116472]: [10.001998639s] [10.001998639s] END
Oct 22 16:46:16 controller kubelet[854]: E1022 16:46:16.892099     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": net/http: TLS handshake timeout
Oct 22 16:46:17 controller kubelet[854]: E1022 16:46:17.369978     854 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"controller.1800d42f915e6919", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"controller", UID:"controller", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"controller"}, FirstTimestamp:time.Date(2024, time.October, 22, 16, 45, 57, 677705497, time.Local), LastTimestamp:time.Date(2024, time.October, 22, 16, 45, 57, 677705497, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"kubelet", ReportingInstance:"controller"}': 'Post "https://192.168.1.120:6443/api/v1/namespaces/default/events": net/http: TLS handshake timeout'(may retry after sleeping)
Oct 22 16:46:17 controller kubelet[854]: E1022 16:46:17.983774     854 eviction_manager.go:258] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"controller\" not found"
Oct 22 16:46:20 controller kubelet[854]: I1022 16:46:20.489956     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:46:22 controller kubelet[854]: E1022 16:46:22.048643     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": read tcp 192.168.1.120:52558->192.168.1.120:6443: read: connection reset by peer" node="controller"
Oct 22 16:46:22 controller kubelet[854]: I1022 16:46:22.422387     854 scope.go:117] "RemoveContainer" containerID="a5311c66994459a794b21ad3af6290536b0b18aa5c827dc7ab6a1c57407f84e8"
Oct 22 16:46:22 controller kubelet[854]: I1022 16:46:22.424606     854 scope.go:117] "RemoveContainer" containerID="1080ade07a1efd5762be2720615c2e03eb7409b1ada63bfeff2add2f78675adf"
Oct 22 16:46:22 controller kubelet[854]: E1022 16:46:22.425922     854 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-apiserver\" with CrashLoopBackOff: \"back-off 10s restarting failed container=kube-apiserver pod=kube-apiserver-controller_kube-system(0e229e334952ac434602f5f643efb497)\"" pod="kube-system/kube-apiserver-controller" podUID="0e229e334952ac434602f5f643efb497"
Oct 22 16:46:23 controller kubelet[854]: E1022 16:46:23.047110     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused - error from a previous attempt: read tcp 192.168.1.120:52544->192.168.1.120:6443: read: connection reset by peer" interval="7s"
Oct 22 16:46:23 controller kubelet[854]: W1022 16:46:23.047217     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused - error from a previous attempt: read tcp 192.168.1.120:49600->192.168.1.120:6443: read: connection reset by peer
Oct 22 16:46:23 controller kubelet[854]: E1022 16:46:23.047271     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://192.168.1.120:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused - error from a previous attempt: read tcp 192.168.1.120:49600->192.168.1.120:6443: read: connection reset by peer
Oct 22 16:46:23 controller kubelet[854]: W1022 16:46:23.047269     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused - error from a previous attempt: read tcp 192.168.1.120:49592->192.168.1.120:6443: read: connection reset by peer
Oct 22 16:46:23 controller kubelet[854]: E1022 16:46:23.047305     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused - error from a previous attempt: read tcp 192.168.1.120:49592->192.168.1.120:6443: read: connection reset by peer
Oct 22 16:46:25 controller kubelet[854]: W1022 16:46:25.900639     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:25 controller kubelet[854]: E1022 16:46:25.900723     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.1.120:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcontroller&limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:27 controller kubelet[854]: W1022 16:46:27.196551     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:27 controller kubelet[854]: E1022 16:46:27.196737     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://192.168.1.120:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:27 controller kubelet[854]: E1022 16:46:27.373658     854 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"controller.1800d42f915e6919", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"controller", UID:"controller", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"controller"}, FirstTimestamp:time.Date(2024, time.October, 22, 16, 45, 57, 677705497, time.Local), LastTimestamp:time.Date(2024, time.October, 22, 16, 45, 57, 677705497, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"kubelet", ReportingInstance:"controller"}': 'Post "https://192.168.1.120:6443/api/v1/namespaces/default/events": dial tcp 192.168.1.120:6443: connect: connection refused'(may retry after sleeping)
Oct 22 16:46:27 controller kubelet[854]: I1022 16:46:27.456681     854 scope.go:117] "RemoveContainer" containerID="1080ade07a1efd5762be2720615c2e03eb7409b1ada63bfeff2add2f78675adf"
Oct 22 16:46:27 controller kubelet[854]: E1022 16:46:27.459372     854 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-apiserver\" with CrashLoopBackOff: \"back-off 10s restarting failed container=kube-apiserver pod=kube-apiserver-controller_kube-system(0e229e334952ac434602f5f643efb497)\"" pod="kube-system/kube-apiserver-controller" podUID="0e229e334952ac434602f5f643efb497"
Oct 22 16:46:27 controller kubelet[854]: E1022 16:46:27.985553     854 eviction_manager.go:258] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"controller\" not found"
Oct 22 16:46:30 controller kubelet[854]: I1022 16:46:30.500852     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:46:30 controller kubelet[854]: E1022 16:46:30.501854     854 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.120:6443/api/v1/nodes\": dial tcp 192.168.1.120:6443: connect: connection refused" node="controller"
Oct 22 16:46:31 controller kubelet[854]: E1022 16:46:31.498036     854 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.120:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/controller?timeout=10s\": dial tcp 192.168.1.120:6443: connect: connection refused" interval="7s"
Oct 22 16:46:31 controller kubelet[854]: W1022 16:46:31.772483     854 reflector.go:535] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:31 controller kubelet[854]: E1022 16:46:31.772715     854 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://192.168.1.120:6443/apis/node.k8s.io/v1/runtimeclasses?limit=500&resourceVersion=0": dial tcp 192.168.1.120:6443: connect: connection refused
Oct 22 16:46:32 controller kubelet[854]: I1022 16:46:32.070015     854 scope.go:117] "RemoveContainer" containerID="1080ade07a1efd5762be2720615c2e03eb7409b1ada63bfeff2add2f78675adf"
Oct 22 16:46:37 controller kubelet[854]: I1022 16:46:37.504324     854 kubelet_node_status.go:70] "Attempting to register node" node="controller"
Oct 22 16:46:39 controller kubelet[854]: E1022 16:46:39.435688     854 eviction_manager.go:258] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"controller\" not found"
Oct 22 16:46:41 controller kubelet[854]: I1022 16:46:41.823315     854 kubelet_node_status.go:108] "Node was previously registered" node="controller"
Oct 22 16:46:41 controller kubelet[854]: I1022 16:46:41.823708     854 kubelet_node_status.go:73] "Successfully registered node" node="controller"
Oct 22 16:46:41 controller kubelet[854]: I1022 16:46:41.839175     854 kuberuntime_manager.go:1538] "Updating runtime config through cri with podcidr" CIDR="10.244.0.0/24"
Oct 22 16:46:41 controller kubelet[854]: I1022 16:46:41.849845     854 kubelet_network.go:61] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.244.0.0/24"
Oct 22 16:46:41 controller kubelet[854]: E1022 16:46:41.975615     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.077716     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.179501     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.281928     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.382275     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.484020     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.585677     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.686220     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.788708     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.890108     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:42 controller kubelet[854]: E1022 16:46:42.990376     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:43 controller kubelet[854]: E1022 16:46:43.092369     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:43 controller kubelet[854]: E1022 16:46:43.193171     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:43 controller kubelet[854]: E1022 16:46:43.294358     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:43 controller kubelet[854]: E1022 16:46:43.394772     854 kubelet_node_status.go:458] "Error getting the current node from lister" err="node \"controller\" not found"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.166501     854 apiserver.go:52] "Watching apiserver"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.199070     854 topology_manager.go:215] "Topology Admit Handler" podUID="808038cc-2532-49d3-a6ae-0c0c1e0f679c" podNamespace="kube-system" podName="kube-proxy-8wjkq"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.199916     854 topology_manager.go:215] "Topology Admit Handler" podUID="4e449720-50d8-43be-b167-0db7c2f7fbee" podNamespace="kube-system" podName="coredns-5dd5756b68-cjgvb"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.200100     854 topology_manager.go:215] "Topology Admit Handler" podUID="c3af59d4-547d-43d3-9449-73762d8ffe7c" podNamespace="kube-system" podName="coredns-5dd5756b68-f8h7p"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.200299     854 topology_manager.go:215] "Topology Admit Handler" podUID="102522a1-79a1-4147-86d3-f39a19b2fe19" podNamespace="kube-flannel" podName="kube-flannel-ds-jw2fn"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.261524     854 desired_state_of_world_populator.go:159] "Finished populating initial desired state of world"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.280380     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-plugin\" (UniqueName: \"kubernetes.io/host-path/102522a1-79a1-4147-86d3-f39a19b2fe19-cni-plugin\") pod \"kube-flannel-ds-jw2fn\" (UID: \"102522a1-79a1-4147-86d3-f39a19b2fe19\") " pod="kube-flannel/kube-flannel-ds-jw2fn"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.282656     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/102522a1-79a1-4147-86d3-f39a19b2fe19-xtables-lock\") pod \"kube-flannel-ds-jw2fn\" (UID: \"102522a1-79a1-4147-86d3-f39a19b2fe19\") " pod="kube-flannel/kube-flannel-ds-jw2fn"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.282740     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/808038cc-2532-49d3-a6ae-0c0c1e0f679c-xtables-lock\") pod \"kube-proxy-8wjkq\" (UID: \"808038cc-2532-49d3-a6ae-0c0c1e0f679c\") " pod="kube-system/kube-proxy-8wjkq"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.282826     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"run\" (UniqueName: \"kubernetes.io/host-path/102522a1-79a1-4147-86d3-f39a19b2fe19-run\") pod \"kube-flannel-ds-jw2fn\" (UID: \"102522a1-79a1-4147-86d3-f39a19b2fe19\") " pod="kube-flannel/kube-flannel-ds-jw2fn"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.282983     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni\" (UniqueName: \"kubernetes.io/host-path/102522a1-79a1-4147-86d3-f39a19b2fe19-cni\") pod \"kube-flannel-ds-jw2fn\" (UID: \"102522a1-79a1-4147-86d3-f39a19b2fe19\") " pod="kube-flannel/kube-flannel-ds-jw2fn"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.283035     854 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/808038cc-2532-49d3-a6ae-0c0c1e0f679c-lib-modules\") pod \"kube-proxy-8wjkq\" (UID: \"808038cc-2532-49d3-a6ae-0c0c1e0f679c\") " pod="kube-system/kube-proxy-8wjkq"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.860974     854 scope.go:117] "RemoveContainer" containerID="76eda554321b3d414c03dbda4537246d50b12e9a8821f4abc151ce625673753a"
Oct 22 16:46:44 controller kubelet[854]: I1022 16:46:44.903939     854 scope.go:117] "RemoveContainer" containerID="646c4415f0002fab9f2a7a7840d854b26406e829440d4bce31f5e5255c4aced7"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.621030     854 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"68f9f4871730d3d2a96986e53c4243408a37237e18068942a42feef9f2eaf7f8\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.621127     854 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"68f9f4871730d3d2a96986e53c4243408a37237e18068942a42feef9f2eaf7f8\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-cjgvb"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.621182     854 kuberuntime_manager.go:1181] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"68f9f4871730d3d2a96986e53c4243408a37237e18068942a42feef9f2eaf7f8\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-cjgvb"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.621319     854 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"coredns-5dd5756b68-cjgvb_kube-system(4e449720-50d8-43be-b167-0db7c2f7fbee)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"coredns-5dd5756b68-cjgvb_kube-system(4e449720-50d8-43be-b167-0db7c2f7fbee)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"68f9f4871730d3d2a96986e53c4243408a37237e18068942a42feef9f2eaf7f8\\\": plugin type=\\\"flannel\\\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/coredns-5dd5756b68-cjgvb" podUID="4e449720-50d8-43be-b167-0db7c2f7fbee"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.745467     854 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"0d991e51892f21406c1afc34faa50fd7033ef232986581ef484e1af3631d108d\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.745549     854 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"0d991e51892f21406c1afc34faa50fd7033ef232986581ef484e1af3631d108d\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-f8h7p"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.745578     854 kuberuntime_manager.go:1181] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"0d991e51892f21406c1afc34faa50fd7033ef232986581ef484e1af3631d108d\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-f8h7p"
Oct 22 16:46:45 controller kubelet[854]: E1022 16:46:45.745731     854 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"coredns-5dd5756b68-f8h7p_kube-system(c3af59d4-547d-43d3-9449-73762d8ffe7c)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"coredns-5dd5756b68-f8h7p_kube-system(c3af59d4-547d-43d3-9449-73762d8ffe7c)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"0d991e51892f21406c1afc34faa50fd7033ef232986581ef484e1af3631d108d\\\": plugin type=\\\"flannel\\\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/coredns-5dd5756b68-f8h7p" podUID="c3af59d4-547d-43d3-9449-73762d8ffe7c"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.719269     854 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"cded7e960fc861fe06ba9ba787b555b67e0cf6e1c289e4aa00f738f07485a19f\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.719416     854 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"cded7e960fc861fe06ba9ba787b555b67e0cf6e1c289e4aa00f738f07485a19f\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-cjgvb"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.719448     854 kuberuntime_manager.go:1181] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"cded7e960fc861fe06ba9ba787b555b67e0cf6e1c289e4aa00f738f07485a19f\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-cjgvb"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.719594     854 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"coredns-5dd5756b68-cjgvb_kube-system(4e449720-50d8-43be-b167-0db7c2f7fbee)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"coredns-5dd5756b68-cjgvb_kube-system(4e449720-50d8-43be-b167-0db7c2f7fbee)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"cded7e960fc861fe06ba9ba787b555b67e0cf6e1c289e4aa00f738f07485a19f\\\": plugin type=\\\"flannel\\\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/coredns-5dd5756b68-cjgvb" podUID="4e449720-50d8-43be-b167-0db7c2f7fbee"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.853187     854 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"b53b0ccd8cab1b1d1b383f4c050d4c263c84f8d7ef1ae0448dc88c331fc34de5\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.853710     854 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"b53b0ccd8cab1b1d1b383f4c050d4c263c84f8d7ef1ae0448dc88c331fc34de5\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-f8h7p"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.853964     854 kuberuntime_manager.go:1181] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"b53b0ccd8cab1b1d1b383f4c050d4c263c84f8d7ef1ae0448dc88c331fc34de5\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-f8h7p"
Oct 22 16:46:46 controller kubelet[854]: E1022 16:46:46.857660     854 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"coredns-5dd5756b68-f8h7p_kube-system(c3af59d4-547d-43d3-9449-73762d8ffe7c)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"coredns-5dd5756b68-f8h7p_kube-system(c3af59d4-547d-43d3-9449-73762d8ffe7c)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"b53b0ccd8cab1b1d1b383f4c050d4c263c84f8d7ef1ae0448dc88c331fc34de5\\\": plugin type=\\\"flannel\\\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/coredns-5dd5756b68-f8h7p" podUID="c3af59d4-547d-43d3-9449-73762d8ffe7c"
Oct 22 16:46:49 controller kubelet[854]: I1022 16:46:49.284307     854 scope.go:117] "RemoveContainer" containerID="fe79ea0ef0b3e717dea101563fcb93c94af797141f590a985aa957f23663849c"
sre@controller:~/flannel$ 

